/**
 * Assignments Database
 * Mock data for course assignments
 */

export default [
  // CS5010 Assignments
  {
    _id: "A101",
    title: "A1 - Design Recipe Practice",
    course: "CS5010",
    description: "Practice using the design recipe to create functions",
    points: 100,
    dueDate: "2025-09-20",
    availableFrom: "2025-09-01",
    availableUntil: "2025-09-20",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Text Entry", "File Uploads"],
  },
  {
    _id: "A102",
    title: "A2 - Data Definitions",
    course: "CS5010",
    description: "Create data definitions for various scenarios",
    points: 100,
    dueDate: "2025-09-27",
    availableFrom: "2025-09-15",
    availableUntil: "2025-09-27",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },
  {
    _id: "A103",
    title: "A3 - Abstraction",
    course: "CS5010",
    description: "Practice abstraction techniques",
    points: 100,
    dueDate: "2025-10-04",
    availableFrom: "2025-09-22",
    availableUntil: "2025-10-04",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },

  // CS5610 Assignments
  {
    _id: "A201",
    title: "A1 - HTML and CSS Basics",
    course: "CS5610",
    description: "Create a personal website using HTML and CSS",
    points: 100,
    dueDate: "2025-09-28",
    availableFrom: "2025-09-20",
    availableUntil: "2025-09-28",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL"],
  },
  {
    _id: "A202",
    title: "A2 - JavaScript Fundamentals",
    course: "CS5610",
    description: "Implement interactive features using JavaScript",
    points: 150,
    dueDate: "2025-10-06",
    availableFrom: "2025-09-30",
    availableUntil: "2025-10-06",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL", "File Uploads"],
  },
  {
    _id: "A203",
    title: "A3 - React Application",
    course: "CS5610",
    description: "Build a React application with components and state",
    points: 200,
    dueDate: "2025-10-20",
    availableFrom: "2025-10-10",
    availableUntil: "2025-10-20",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Percentage",
    submissionType: "Online",
    onlineEntryOptions: ["Website URL", "File Uploads"],
  },

  // CS5800 Assignments
  {
    _id: "A301",
    title: "Homework 1 - Algorithm Analysis",
    course: "CS5800",
    description: "Analyze the time complexity of given algorithms",
    points: 100,
    dueDate: "2025-09-25",
    availableFrom: "2025-09-15",
    availableUntil: "2025-09-25",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },
  {
    _id: "A302",
    title: "Homework 2 - Sorting Algorithms",
    course: "CS5800",
    description: "Implement and compare different sorting algorithms",
    points: 150,
    dueDate: "2025-10-02",
    availableFrom: "2025-09-22",
    availableUntil: "2025-10-02",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },

  // CS6140 Assignments
  {
    _id: "A401",
    title: "Lab 1 - Linear Regression",
    course: "CS6140",
    description: "Implement linear regression from scratch",
    points: 100,
    dueDate: "2025-09-30",
    availableFrom: "2025-09-20",
    availableUntil: "2025-09-30",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },
  {
    _id: "A402",
    title: "Lab 2 - Classification",
    course: "CS6140",
    description: "Build a classification model",
    points: 150,
    dueDate: "2025-10-07",
    availableFrom: "2025-09-27",
    availableUntil: "2025-10-07",
    assignmentGroup: "ASSIGNMENTS",
    displayGradeAs: "Points",
    submissionType: "Online",
    onlineEntryOptions: ["File Uploads"],
  },
];
